### PR TITLE
Feature/add goal

### PR DESCRIPTION
**Pull request by jamesmccann-zz**
@jarsbe @mattnydam this PR adds the "new goal" form to the home screen/goals list.

Pic related:

pennypot-add-goal

### CODE REVIEW

**Comment by jamesmccann-zz** [comment]
Also looks a bit nicer on Android L

pennypot-add-goal-mat

**Comment by mattnydam** [comment]
That's awesome!

**Comment by jamesmccann-zz** [comment]
@mattnydam cheers bro!

**Comment by jackcallister** [comment]
Damn that's slick. Teach me android @jamesmccann

**Pull request merged**
